import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DynamicManifest from './DynamicManifest';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // We'll set a default manifest here, but it will be overridden dynamically
  // manifest: "/api/manifest/default",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DynamicManifest />
        {children}
      </body>
    </html>
  );
}